# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: mcgriff3325
open_collective: mcgriff3325
ko_fi: mcgriff3325
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: mcgriff3325
issuehunt: mcgriff3325
otechie: mcgriff3325
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
